name: 'HarmonyOS-build'
description: 'This Github action helps build and analyse HMOS libraries'
branding:
  icon: award
  color: red
runs:
  using: "composite"
  steps:
    - name: Build
      env:
        OHOS_SDK_HOME: ${{ github.action_path }}
        npm.dir: 'C:\hostedtoolcache\windows\node\14.18.3\x64'
      shell: cmd
      id: main
      working-directory: ${{ github.workspace }}
      run: |
        xcopy ${{ github.action_path }}\config ${{ github.workspace }}\config\
        ${{ github.action_path }}/run.bat
